### PR TITLE
Update reports_model.js

### LINKED ISSUE #1: [Feat]:You should add the authentication with jwt tokens for more security
### Due to your current authentication there is the high chances for hackers to hack it. so use jwt token

### PR DESCRIPTION
**Pull request by devrushikesh**
fixes #1

### CODE REVIEW

**Comment by ledgend-rushi** [comment]
is it good.

**Comment by devrushikesh** [comment]
yes, its good i am sure

**Comment by devrushikesh** [comment]
did you done that

**Comment by ledgend-rushi** [comment]
yes what happened

**Pull request merged**
